version: '3.8'

services:
  drying-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - PORT=${PORT}
      - HOST=${HOST}
      - DEBUG=${DEBUG}
    volumes:
      - ./test_images:/app/test_images
      - ./test_results:/app/test_results
    restart: always
    networks:
      - drying-network

networks:
  drying-network:
    driver: bridge 