version: '3.8'

services:
  drying-assistant:
    build: .
    ports:
      - "7862:7862"
    environment:
      - PORT=7862
      - HOST=0.0.0.0
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
    volumes:
      - ./test_images:/app/test_images
      - ./test_results:/app/test_results
    restart: unless-stopped 