services:
  - type: web
    name: drying-assistant
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STABILITY_API_KEY
        sync: false
      - key: PORT
        value: "7860"
      - key: HOST
        value: "0.0.0.0"
      - key: DEBUG
        value: "false" 